// Generated by assets-src/bookcase/measure-shelves.mjs — do not edit by hand.
// Measured from public/models/bookcase.glb, in world metres after BOOKCASE_SCALE.
//
// Origin: the Bookcase is centred on x = 0, stands on y = 0 and has the back of
// its case at z = 0, so the front edge is at z = BOOKCASE_SIZE.depth. +z is the
// side the camera looks from. World space equals model space × BOOKCASE_SCALE.

/** One usable Shelf surface: the board of one bay on one Shelf. */
export interface ShelfSlot {
  /** 0 = leftmost bay as seen from the front. */
  bay: number
  /** 0 = topmost Shelf. */
  shelf: number
  /** Height of the Shelf surface a Book stands on. */
  y: number
  /** Left edge of the usable surface (inside the divider). */
  xStart: number
  /** Right edge of the usable surface (inside the divider). */
  xEnd: number
  /** Front edge of the usable surface. */
  zFront: number
  /** Back edge of the usable surface (the back panel). */
  zBack: number
  /** Vertical room to the underside of the board above — the Book height cap. */
  clearance: number
}

/** Model units × this = world metres. */
export const BOOKCASE_SCALE = 0.532035

/** Outer size of the Bookcase in world metres. */
export const BOOKCASE_SIZE = { width: 2.0406, height: 2.4, depth: 0.3611 }

/** Bays per Bookcase, left to right. */
export const BAY_COUNT = 4

/** Shelves per bay, top to bottom. */
export const SHELF_COUNT = 6

/** All 24 Shelf surfaces in reading order: top to bottom, left to right. */
export const SHELF_SLOTS: ShelfSlot[] = [
  { bay: 0, shelf: 0, y: 1.9659, xStart: -0.9311, xEnd: -0.5054, zFront: 0.1985, zBack: 0.0542, clearance: 0.2464 },
  { bay: 1, shelf: 0, y: 1.9659, xStart: -0.4522, xEnd: -0.0266, zFront: 0.1985, zBack: 0.0542, clearance: 0.2464 },
  { bay: 2, shelf: 0, y: 1.9659, xStart: 0.0266, xEnd: 0.4522, zFront: 0.1985, zBack: 0.0542, clearance: 0.2464 },
  { bay: 3, shelf: 0, y: 1.9659, xStart: 0.5054, xEnd: 0.9311, zFront: 0.1985, zBack: 0.0542, clearance: 0.2464 },
  { bay: 0, shelf: 1, y: 1.6765, xStart: -0.9311, xEnd: -0.5054, zFront: 0.1985, zBack: 0.0542, clearance: 0.2743 },
  { bay: 1, shelf: 1, y: 1.6765, xStart: -0.4522, xEnd: -0.0266, zFront: 0.1985, zBack: 0.0542, clearance: 0.2743 },
  { bay: 2, shelf: 1, y: 1.6765, xStart: 0.0266, xEnd: 0.4522, zFront: 0.1985, zBack: 0.0542, clearance: 0.2743 },
  { bay: 3, shelf: 1, y: 1.6765, xStart: 0.5054, xEnd: 0.9311, zFront: 0.1985, zBack: 0.0542, clearance: 0.2743 },
  { bay: 0, shelf: 2, y: 1.3863, xStart: -0.9311, xEnd: -0.5054, zFront: 0.1985, zBack: 0.0542, clearance: 0.275 },
  { bay: 1, shelf: 2, y: 1.3863, xStart: -0.4522, xEnd: -0.0266, zFront: 0.1985, zBack: 0.0542, clearance: 0.275 },
  { bay: 2, shelf: 2, y: 1.3863, xStart: 0.0266, xEnd: 0.4522, zFront: 0.1985, zBack: 0.0542, clearance: 0.275 },
  { bay: 3, shelf: 2, y: 1.3863, xStart: 0.5054, xEnd: 0.9311, zFront: 0.1985, zBack: 0.0542, clearance: 0.275 },
  { bay: 0, shelf: 3, y: 1.0969, xStart: -0.9311, xEnd: -0.5054, zFront: 0.1985, zBack: 0.0542, clearance: 0.2743 },
  { bay: 1, shelf: 3, y: 1.0969, xStart: -0.4522, xEnd: -0.0266, zFront: 0.1985, zBack: 0.0542, clearance: 0.2743 },
  { bay: 2, shelf: 3, y: 1.0969, xStart: 0.0266, xEnd: 0.4522, zFront: 0.1985, zBack: 0.0542, clearance: 0.2743 },
  { bay: 3, shelf: 3, y: 1.0969, xStart: 0.5054, xEnd: 0.9311, zFront: 0.1985, zBack: 0.0542, clearance: 0.2743 },
  { bay: 0, shelf: 4, y: 0.8075, xStart: -0.9311, xEnd: -0.5054, zFront: 0.1985, zBack: 0.0542, clearance: 0.2743 },
  { bay: 1, shelf: 4, y: 0.8075, xStart: -0.4522, xEnd: -0.0266, zFront: 0.1985, zBack: 0.0542, clearance: 0.2743 },
  { bay: 2, shelf: 4, y: 0.8075, xStart: 0.0266, xEnd: 0.4522, zFront: 0.1985, zBack: 0.0542, clearance: 0.2743 },
  { bay: 3, shelf: 4, y: 0.8075, xStart: 0.5054, xEnd: 0.9311, zFront: 0.1985, zBack: 0.0542, clearance: 0.2743 },
  { bay: 0, shelf: 5, y: 0.5217, xStart: -0.9311, xEnd: -0.5054, zFront: 0.212, zBack: 0.0542, clearance: 0.2706 },
  { bay: 1, shelf: 5, y: 0.5217, xStart: -0.4522, xEnd: -0.0266, zFront: 0.212, zBack: 0.0542, clearance: 0.2706 },
  { bay: 2, shelf: 5, y: 0.5217, xStart: 0.0266, xEnd: 0.4522, zFront: 0.212, zBack: 0.0542, clearance: 0.2706 },
  { bay: 3, shelf: 5, y: 0.5217, xStart: 0.5054, xEnd: 0.9311, zFront: 0.212, zBack: 0.0542, clearance: 0.2706 },
]

/** The tallest Book any Shelf can take, in world metres. */
export const MAX_BOOK_HEIGHT = 0.2464

/** Usable depth of a Shelf, in world metres. */
export const SHELF_DEPTH = 0.1443
